import type { Metadata } from 'next';
import { notFound, redirect } from 'next/navigation';
import { Suspense } from 'react';
import { Header } from '@/components/Header';
import { ResourceCard } from '@/components/ResourceCard';
import { PaginationNav } from '@/components/PaginationNav';
import { getFilteredResources } from '@/lib/queries';

const CATEGORIES: Record<string, { name: string; description: string }> = {
  'mcp-servers': {
    name: 'MCP Servers',
    description: 'Browse {count}+ MCP servers for Google Antigravity IDE. Find the best tool integrations, APIs and context providers for your Antigravity workspace.',
  },
  'skills': {
    name: 'Skills',
    description: 'Browse {count}+ Skills for Google Antigravity IDE. Agent capabilities, SKILL.md packages and pre-built skills for your Antigravity workflows.',
  },
  'rules': {
    name: 'Rules',
    description: 'Browse {count}+ rules for Google Antigravity IDE. Custom AI behaviours, coding standards and context rules to shape your Antigravity experience.',
  },
  'prompts': {
    name: 'Prompts',
    description: 'Browse {count}+ prompts for Google Antigravity IDE. System prompts, task prompts and instruction sets optimised for Gemini and Antigravity.',
  },
  'agents': {
    name: 'Agents',
    description: 'Browse {count}+ agents for Google Antigravity IDE. Pre-configured agentic setups and agent templates for complex workflows.',
  },
  'workflows': {
    name: 'Workflows',
    description: 'Browse {count}+ workflows for Google Antigravity IDE. Automation templates, multi-step flows and saved workflow configurations.',
  },
  'boilerplates': {
    name: 'Boilerplates',
    description: 'Browse {count}+ boilerplates for Google Antigravity IDE. Project starters, repo templates and scaffolds configured for Antigravity.',
  },
  'troubleshooting': {
    name: 'Troubleshooting',
    description: 'Browse {count}+ troubleshooting guides for Google Antigravity IDE. Common errors, fixes and how-to guides for Antigravity users.',
  },
  'tutorials': {
    name: 'Tutorials',
    description: 'Browse {count}+ tutorials for Google Antigravity IDE. Step-by-step guides for getting the most out of Antigravity and Gemini.',
  },
  'cheatsheets': {
    name: 'Cheatsheets',
    description: 'Browse {count}+ cheatsheets for Google Antigravity IDE. Quick reference cards for commands, shortcuts and configurations.',
  },
};

const ITEMS_PER_PAGE = 50;

export async function generateStaticParams() {
  const params: { slug: string; pageNum: string }[] = [];

  for (const slug of Object.keys(CATEGORIES)) {
    // 1. Fetch total count for this category (all LIVE resources)
    const result = await getFilteredResources({
      categories: [slug],
      tags: [],
      badgeTypes: [],
      search: '',
      sort: 'recommended',
      group: undefined,
    }, 1, 1);

    const totalLive = result.totalCount;
    const totalPages = Math.ceil(totalLive / ITEMS_PER_PAGE);

    // 2. Generate params for pages 2 through totalPages
    for (let page = 2; page <= totalPages; page++) {
      params.push({ slug, pageNum: String(page) });
    }
  }

  return params;
}

export const revalidate = 3600;
// Allow paths not generated by generateStaticParams to render and be cached at runtime
export const dynamicParams = true;

export async function generateMetadata({ params }: { params: Promise<{ slug: string; pageNum: string }> }): Promise<Metadata> {
  const { slug, pageNum } = await params;
  const category = CATEGORIES[slug];
  
  if (!category) return {};

  const page = parseInt(pageNum, 10);
  if (isNaN(page) || page < 2) return {};

  const result = await getFilteredResources({
      categories: [slug],
      tags: [],
      badgeTypes: [],
      search: '',
      sort: 'recommended',
      group: undefined,
  }, 1, 1);

  const totalPages = Math.ceil(result.totalCount / ITEMS_PER_PAGE);

  const title = `${category.name} for Google Antigravity IDE — Page ${page}`;
  const description = `Browse ${category.name} resources, page ${page} of ${totalPages}. ${category.description.replace('{count}+', '')}`;

  return {
    title,
    description,
    alternates: {
      canonical: `https://www.googleantigravity.directory/${slug}/page/${page}`,
    },
    openGraph: {
      title,
      description,
      type: 'website',
      url: `https://www.googleantigravity.directory/${slug}/page/${page}`,
    },
  };
}

export default async function CategoryPaginationPage({ params }: { params: Promise<{ slug: string; pageNum: string }> }) {
  const { slug, pageNum } = await params;
  const category = CATEGORIES[slug];

  // 1. Validate category
  if (!category) {
    notFound();
  }

  // 2. Validate page number
  const page = parseInt(pageNum, 10);
  if (isNaN(page) || page < 1) {
    notFound();
  }

  // 3. Redirect page 1 to base slug
  if (page === 1) {
    redirect(`/${slug}`);
  }

  // 4a. Count all LIVE resources (featured + organic) for header display and pagination nav
  const countResult = await getFilteredResources({
      categories: [slug],
      tags: [],
      badgeTypes: [],
      search: '',
      sort: 'recommended',
      group: undefined,
  }, 1, 1);

  const totalLive = countResult.totalCount;
  const totalPages = Math.ceil(totalLive / ITEMS_PER_PAGE);

  // 4b. Fetch 50 organic resources for this page (featured resources appear on page 1 via interleaving)
  const result = await getFilteredResources({
      categories: [slug],
      tags: [],
      badgeTypes: [],
      search: '',
      sort: 'recommended',
      group: undefined,
      isSponsored: false
  }, page, ITEMS_PER_PAGE);

  // 5. 404 if beyond last page
  if (page > totalPages && totalLive > 0) {
    notFound();
  }

  // 6. Handle edge case for completely empty category requesting page 2
  if (result.resources.length === 0) {
    notFound();
  }

  return (
    <>
      <Header />
      <main className="min-h-screen bg-black text-white">
        <section className="pt-24 pb-8 px-4 max-w-[1920px] mx-auto sm:px-6 lg:px-8">
          <h1 className="text-4xl md:text-5xl font-black text-white tracking-tighter">
            {category.name} for Google Antigravity IDE
            <span className="block text-2xl font-normal text-gray-400 mt-2 tracking-normal">Page {page} of {totalPages}</span>
          </h1>
          <p className="mt-3 text-gray-400 text-base">
            {totalLive.toLocaleString()} resources
          </p>
        </section>

        <section className="py-8 max-w-[1920px] mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col gap-3">
            {result.resources.map((resource) => (
              <ResourceCard key={resource.id} resource={resource} />
            ))}
          </div>

          <Suspense fallback={null}>
            <PaginationNav 
              currentPage={page} 
              totalPages={totalPages} 
              basePath={`/${slug}`} 
            />
          </Suspense>
        </section>
      </main>
    </>
  );
}
